Fix problem `AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'`
Which is mentioned [here](https://github.com/Fannovel16/comfyui_controlnet_aux/issues/60)